create table grabweibo (
created_at	varchar2(255)	,
mid	number	,
content	varchar2(1000)	,
source	varchar2(255)	,
favorited	varchar2(10)	,
truncated	varchar2(10)	,
thumbnail_pic	varchar2(255)	,
bmiddle_pic	varchar2(255)	,
original_pic	varchar2(255)	,
latitude	number	,
longitude	number	,
user_id	number	,
user_screen_name	varchar2(255)	,
user_location	varchar2(255)	,
user_description	varchar2(3000)	,
user_profile_img_url	varchar2(255)	,
user_profile_url	varchar2(255)	,
user_gender	varchar2(255)	,
user_followers_count	number	,
user_friends_count	number	,
user_statuses_count	number	,
user_favourites_count	number	,
user_created_at	varchar2(255)	,
user_verified	varchar2(10)	,
user_avatar_large	varchar2(255)	,
user_verified_reason	varchar2(255)	,
retweeted_status_id	number	,
reposts_count	number	,
comments_count	number	,
type	number	
);
